Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  # if you make a categories controller, this would be the :show
  get '/products/category/:catid',
      to: 'products#category',
      as: 'category'

  # AA note: this was the old route per RichOnRails
  # resource :cart, only: [:show]
  get '/products/cart',
      to: 'products#cart',
      as: 'cart'

  get '/products/checkout',
      to: 'products#checkout',
      as: 'checkout'

  post '/products/place_order',
       to: 'products#place_order',
       as: 'order_confirmation'

  get '/products/search_product/',
      to: 'products#search_product'

  # ie. like :show
  get '/products/item/:id',
      to: 'products#item',
      as: 'product'



  # get '/products/search_keyword/', to: 'products#search_keyword'
  # per richonrails.com
  resources :products, only: [:index] do
    member do
      post :add_product_to_order
      post :update_product_on_order
      post :remove_product_from_order
    end
  end

  # note: whenever you use %i, [] should become ()
  resources :order_items, only: %i(create update destroy)

  # autogenerated routes for customer
  get 'customer/login'
  get 'customer/register'
  get 'customer/show'
  get 'customer/edit'
  get 'customer/deactivate'
end
